[package]
name = "aoc24"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "day1"
test = false
bench = false

[dependencies]
fxhash = "0.2.1"
itertools = "0.13.0"
maplit = "1.0.2"
nom = "7.1.3"
pathfinding = "4.12.0"
